FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y git build-essential cmake clang libssl-dev wget \
    g++ python-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev \
    libwebsocketpp-dev \
    libx11-dev libglu1-mesa-dev mesa-common-dev freeglut3-dev

    #c++
    #websocketpp
    #websocketpp
    #physx build用